packaging_format = 2

id = "lidarr"
name = "Lidarr"
description.en = "Music collection manager for Usenet and BitTorrent users"
description.fr = "Gestionnaire de discothèque pour utilisateurs de Usenet et BitTorrent"

version = "1.2.6.3313~ynh2"

maintainers = ["tituspijean"]

[upstream]
license = "GPL-3.0-only"
website = "https://lidarr.audio"
admindoc = "https://wiki.servarr.com/Lidarr"
code = "https://github.com/Lidarr/Lidarr"

[integration]
yunohost = ">= 11.1.15"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/lidarr"

    [install.admin]
    type = "user"

[resources]
        [resources.sources.main]
        arm64.url = "https://github.com/Lidarr/Lidarr/releases/download/v1.2.6.3313/Lidarr.master.1.2.6.3313.linux-core-arm64.tar.gz"
        arm64.sha256 = "10d7504278f1345c956274ddc59b9a48ee2827bb1de0e6bd4cbb3cc6ef77a798"
        amd64.url = "https://github.com/Lidarr/Lidarr/releases/download/v1.2.6.3313/Lidarr.master.1.2.6.3313.linux-core-x64.tar.gz"
        amd64.sha256 = "7d87ea92fde8f5a972d9b818e62899113b382d97eb6c919677b5de44fe274eed"
        armhf.url = "https://github.com/Lidarr/Lidarr/releases/download/v1.2.6.3313/Lidarr.master.1.2.6.3313.linux-core-arm.tar.gz"
        armhf.sha256 = "61ec3a2eac61d1d94e61b0c3085cd7c1c640c7bbaddf9ab1878b72d4f0990c5a"
        i386.url = "https://github.com/Lidarr/Lidarr/releases/download/v1.2.6.3313/Lidarr.master.1.2.6.3313.linux-core-x86.tar.gz"
        i386.sha256 = "bff2aa79c5681c6455bffd99f1eecd0a94edfd180fdbbc0ede232486a0d215aa"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.amd64 = ".*linux-core-x64.tar.gz"
        autoupdate.asset.i386 = ".*linux-core-x86.tar.gz"
        autoupdate.asset.armhf = ".*linux-core-arm.tar.gz"
        autoupdate.asset.arm64 = ".*linux-core-arm64.tar.gz"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    api.main.url = "/api"
    api.allowed = "visitors"
    api.show_tile = false
    api.protected = true

    [resources.apt]
    packages = "curl mediainfo sqlite3"
