packaging_format = 2

id = "lidarr"
name = "Lidarr"
description.en = "Music collection manager for Usenet and BitTorrent users"
description.fr = "Gestionnaire de discothèque pour utilisateurs de Usenet et BitTorrent"

version = "2.5.3.4341~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "GPL-3.0-only"
website = "https://lidarr.audio"
admindoc = "https://wiki.servarr.com/Lidarr"
code = "https://github.com/Lidarr/Lidarr"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/lidarr"

    [install.init_main_permission]
    type = "group"
    default = "admins"
    help.en = "Select which group should be able to access and configure the app. Do not select Visitors!"
    help.fr = "Sélectionnez quel groupe devrait pouvoir configurer et accéder à l'application. Ne choisissez pas les Visiteurs !"

[resources]
        [resources.sources.main]
        arm64.url = "https://github.com/Lidarr/Lidarr/releases/download/v2.5.3.4341/Lidarr.master.2.5.3.4341.linux-core-arm64.tar.gz"
        arm64.sha256 = "4aa444eb68483a6684ea4032bbbf74dce883402d9bc9dfd0e12d562b1a48c2e5"
        amd64.url = "https://github.com/Lidarr/Lidarr/releases/download/v2.5.3.4341/Lidarr.master.2.5.3.4341.linux-core-x64.tar.gz"
        amd64.sha256 = "46bc4677de8ef6f16d051e4010a4ebe7c5df1f36124f74d6dde1bde7ee6fb070"
        armhf.url = "https://github.com/Lidarr/Lidarr/releases/download/v2.5.3.4341/Lidarr.master.2.5.3.4341.linux-core-arm.tar.gz"
        armhf.sha256 = "9c553ed8b410811fd18f48f4523eb3bf57f527328709bfd2d3c6d396f7afaaa3"
        i386.url = "https://github.com/Lidarr/Lidarr/releases/download/v2.5.3.4341/Lidarr.master.2.5.3.4341.linux-core-x86.tar.gz"
        i386.sha256 = "19b0aea048b9ee5363854ac0f954393b1e493aea96c13bb9c5034e5db1c4bc3b"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.amd64 = ".*linux-core-x64.tar.gz"
        autoupdate.asset.i386 = ".*linux-core-x86.tar.gz"
        autoupdate.asset.armhf = ".*linux-core-arm.tar.gz"
        autoupdate.asset.arm64 = ".*linux-core-arm64.tar.gz"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["logs"]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.allowed = "visitors"
    api.show_tile = false
    api.protected = true

    [resources.apt]
    packages = "curl, mediainfo, sqlite3"
