packaging_format = 2

id = "lidarr"
name = "Lidarr"
description.en = "Music collection manager for Usenet and BitTorrent users"
description.fr = "Gestionnaire de discothèque pour utilisateurs de Usenet et BitTorrent"

version = "1.3.5.3530~ynh2"

maintainers = ["tituspijean"]

[upstream]
license = "GPL-3.0-only"
website = "https://lidarr.audio"
admindoc = "https://wiki.servarr.com/Lidarr"
code = "https://github.com/Lidarr/Lidarr"

[integration]
yunohost = ">= 11.1.19"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/lidarr"

    [install.admin]
    type = "user"

[resources]
        [resources.sources.main]
        arm64.url = "https://github.com/Lidarr/Lidarr/releases/download/v1.3.5.3530/Lidarr.master.1.3.5.3530.linux-core-arm64.tar.gz"
        arm64.sha256 = "c4c4696e0dfb43d5484628a8cb79144b4d0cd33c424f51b8dfda4d59d8127ba0"
        amd64.url = "https://github.com/Lidarr/Lidarr/releases/download/v1.3.5.3530/Lidarr.master.1.3.5.3530.linux-core-x64.tar.gz"
        amd64.sha256 = "0e976c83de76870deb6b6e3f44479d7e6fd2ddc3a871f4abc63479bc63bf6f91"
        armhf.url = "https://github.com/Lidarr/Lidarr/releases/download/v1.3.5.3530/Lidarr.master.1.3.5.3530.linux-core-arm.tar.gz"
        armhf.sha256 = "764fb0c756c6c8f4d4ea4156158e37ae0e68fca234989051fdfe533d3e3ae93c"
        i386.url = "https://github.com/Lidarr/Lidarr/releases/download/v1.3.5.3530/Lidarr.master.1.3.5.3530.linux-core-x86.tar.gz"
        i386.sha256 = "5b531cfe81b8688c1f34fcebee35b67ee72ee3c7afc2b616cd5514eb7fee9823"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.amd64 = ".*linux-core-x64.tar.gz"
        autoupdate.asset.i386 = ".*linux-core-x86.tar.gz"
        autoupdate.asset.armhf = ".*linux-core-arm.tar.gz"
        autoupdate.asset.arm64 = ".*linux-core-arm64.tar.gz"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["logs"]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.allowed = "visitors"
    api.show_tile = false
    api.protected = true

    [resources.apt]
    packages = "curl mediainfo sqlite3"
