packaging_format = 2

id = "lidarr"
name = "Lidarr"
description.en = "Music collection manager for Usenet and BitTorrent users"
description.fr = "Gestionnaire de discothèque pour utilisateurs de Usenet et BitTorrent"

version = "1.1.4.3027~ynh2"

maintainers = ["tituspijean"]

[upstream]
license = "GPL-3.0-only"
website = "https://lidarr.audio"
admindoc = "https://wiki.servarr.com/Lidarr"
code = "https://github.com/Lidarr/Lidarr"

[integration]
yunohost = ">= 11.1.19"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/lidarr"

    [install.admin]
    type = "user"

[resources]
        [resources.sources.main]
        arm64.url = "https://github.com/Lidarr/Lidarr/releases/download/v1.1.4.3027/Lidarr.master.1.1.4.3027.linux-core-arm64.tar.gz"
        arm64.sha256 = "8ab64b41f78602433a99be845c2dadbac972c3b41805983f6916f42f1ec22450"
        amd64.url = "https://github.com/Lidarr/Lidarr/releases/download/v1.1.4.3027/Lidarr.master.1.1.4.3027.linux-core-x64.tar.gz"
        amd64.sha256 = "246bf849738d567711756aadaaf2a70562579e9d7a0162f216f50b4d63e60207"
        armhf.url = "https://github.com/Lidarr/Lidarr/releases/download/v1.1.4.3027/Lidarr.master.1.1.4.3027.linux-core-arm.tar.gz"
        armhf.sha256 = "d6d9b58f025c9f83b5aa3ad2416b6cfcf4717a398ca6cabd9cbb9c85adfe81b4"
        i386.url = "https://github.com/Lidarr/Lidarr/releases/download/v1.1.4.3027/Lidarr.master.1.1.4.3027.linux-core-x86.tar.gz"
        i386.sha256 = "1677d199ee1c60b93d8de0ebb308bc84d871086560237bb8d0767126ccaa0baa"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.amd64 = ".*linux-core-x64.tar.gz"
        autoupdate.asset.i386 = ".*linux-core-x86.tar.gz"
        autoupdate.asset.armhf = ".*linux-core-arm.tar.gz"
        autoupdate.asset.arm64 = ".*linux-core-arm64.tar.gz"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["logs"]

    [resources.permissions]
    main.url = "/"
    api.main.url = "/api"
    api.allowed = "visitors"
    api.show_tile = false
    api.protected = true

    [resources.apt]
    packages = "curl mediainfo sqlite3"
