packaging_format = 2

id = "lidarr"
name = "Lidarr"
description.en = "Music collection manager for Usenet and BitTorrent users"
description.fr = "Gestionnaire de discothèque pour utilisateurs de Usenet et BitTorrent"

version = "2.9.6.4552~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "GPL-3.0-only"
website = "https://lidarr.audio"
admindoc = "https://wiki.servarr.com/Lidarr"
code = "https://github.com/Lidarr/Lidarr"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/lidarr"

    [install.init_main_permission]
    type = "group"
    default = "admins"
    help.en = "Select which group should be able to access and configure the app. Do not select Visitors!"
    help.fr = "Sélectionnez quel groupe devrait pouvoir configurer et accéder à l'application. Ne choisissez pas les Visiteurs !"

[resources]
        [resources.sources.main]
        arm64.url = "https://github.com/Lidarr/Lidarr/releases/download/v2.9.6.4552/Lidarr.master.2.9.6.4552.linux-core-arm64.tar.gz"
        arm64.sha256 = "2618f0a70828d6f465b964f3a67d20775eee208debc3a38f57ff925bc4cca254"
        amd64.url = "https://github.com/Lidarr/Lidarr/releases/download/v2.9.6.4552/Lidarr.master.2.9.6.4552.linux-core-x64.tar.gz"
        amd64.sha256 = "7e039ed3164c7a979cf830e2ffa2aad63e4456ec38e4882faefb9c7679258f5c"
        armhf.url = "https://github.com/Lidarr/Lidarr/releases/download/v2.9.6.4552/Lidarr.master.2.9.6.4552.linux-core-arm.tar.gz"
        armhf.sha256 = "a4d9e721957f12bd8c4c5c5ea95dd4d98910d79be24ca9634f3103cd37d5e100"
        i386.url = "https://github.com/Lidarr/Lidarr/releases/download/v2.9.6.4552/Lidarr.master.2.9.6.4552.linux-core-x86.tar.gz"
        i386.sha256 = "2dc8aa31e80fe547c9926d78c4e8c1e83de5d30fab3c1485bb3adb4698d1264d"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.amd64 = ".*linux-core-x64.tar.gz"
        autoupdate.asset.i386 = ".*linux-core-x86.tar.gz"
        autoupdate.asset.armhf = ".*linux-core-arm.tar.gz"
        autoupdate.asset.arm64 = ".*linux-core-arm64.tar.gz"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["logs"]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.allowed = "visitors"
    api.show_tile = false
    api.protected = true

    [resources.apt]
    packages = "curl, mediainfo, sqlite3"
