packaging_format = 2

id = "lidarr"
name = "Lidarr"
description.en = "Music collection manager for Usenet and BitTorrent users"
description.fr = "Gestionnaire de discothèque pour utilisateurs de Usenet et BitTorrent"

version = "2.12.4.4658~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "GPL-3.0-only"
website = "https://lidarr.audio"
admindoc = "https://wiki.servarr.com/Lidarr"
code = "https://github.com/Lidarr/Lidarr"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/lidarr"

    [install.init_main_permission]
    type = "group"
    default = "admins"
    help.en = "Select which group should be able to access and configure the app. Do not select Visitors!"
    help.fr = "Sélectionnez quel groupe devrait pouvoir configurer et accéder à l'application. Ne choisissez pas les Visiteurs !"

[resources]
        [resources.sources.main]
        arm64.url = "https://github.com/Lidarr/Lidarr/releases/download/v2.12.4.4658/Lidarr.master.2.12.4.4658.linux-core-arm64.tar.gz"
        arm64.sha256 = "f59bf460247b0af81c0c51985ee739e418459881f58a579df560de12fc003282"
        amd64.url = "https://github.com/Lidarr/Lidarr/releases/download/v2.12.4.4658/Lidarr.master.2.12.4.4658.linux-core-x64.tar.gz"
        amd64.sha256 = "b6d6d08fa198b8a79d0c4745f2f519726734025b994baa4f0b918241352eece3"
        armhf.url = "https://github.com/Lidarr/Lidarr/releases/download/v2.12.4.4658/Lidarr.master.2.12.4.4658.linux-core-arm.tar.gz"
        armhf.sha256 = "b09cb0d02c6d12b31bd04031bca62e8e6fff539f1e5de85cf83c5d377f3edd24"
        i386.url = "https://github.com/Lidarr/Lidarr/releases/download/v2.12.4.4658/Lidarr.master.2.12.4.4658.linux-core-x86.tar.gz"
        i386.sha256 = "d4540c9764b84cbd9a6b2b5dcb406297e791f3cc9a723dda3f28dfb1db310213"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.amd64 = ".*linux-core-x64.tar.gz"
        autoupdate.asset.i386 = ".*linux-core-x86.tar.gz"
        autoupdate.asset.armhf = ".*linux-core-arm.tar.gz"
        autoupdate.asset.arm64 = ".*linux-core-arm64.tar.gz"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["logs"]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.allowed = "visitors"
    api.show_tile = false
    api.protected = true

    [resources.apt]
    packages = "curl, mediainfo, sqlite3"
