#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop" --log_path="systemd"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd

# Use logrotate to manage app-specific logfile(s)
ynh_config_add_logrotate "$data_dir/logs"

yunohost service add $app --description="Lidarr daemon" --log="$data_dir/logs/lidarr.txt"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating the configuration file.."

# Add newline at end of file if required
if [ -e "$data_dir/config.xml" ]; then
    sed -i -e '$a\' "$data_dir/config.xml"
fi

ynh_config_add --template="config.xml" --destination="$data_dir/config.xml"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start" --log_path="systemd" --wait_until="Application started"

#=================================================
# END OF SCRIPT
#=================================================

# Let's wait a bit for migrations to happen
if ynh_in_ci_tests; then
    sleep 5
fi

ynh_script_progression "Upgrade of $app completed"
