#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# CHECK VERSION
#=================================================

upgrade_type=$(ynh_check_app_version_changed)

#=================================================
# STANDARD UPGRADE STEPS
#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Stopping a systemd service..." --weight=1

ynh_systemd_action --service_name=$app --action="stop" --log_path="systemd"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

if [ "$upgrade_type" == "UPGRADE_APP" ]
then
	ynh_script_progression --message="Upgrading source files..." --weight=3

	# Download, check integrity, uncompress and patch the source from app.src
	ynh_setup_source --dest_dir="$install_dir" 
fi

chmod -R o-rwx "$install_dir"
chown -R $app: "$install_dir"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Upgrading system configurations related to $app..." --weight=1

# Create a dedicated NGINX config
ynh_add_nginx_config

# Create a dedicated systemd config
ynh_add_systemd_config

# Use logrotate to manage app-specific logfile(s)
ynh_use_logrotate --non-append --logfile="$data_dir/logs"

yunohost service add $app --description="Lidarr daemon" --log="$data_dir/logs/lidarr.txt"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression --message="Updating the configuration file.." --weight=1

# Add newline at end of file if required
if [ -e "$data_dir/config.xml" ]; then
    sed -i -e '$a\' "$data_dir/config.xml"
fi

ynh_add_config --template="../conf/config.xml" --destination="$data_dir/config.xml"

chmod 400 "$data_dir/config.xml"
chown $app:$app "$data_dir/config.xml"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." --weight=2

ynh_systemd_action --service_name=$app --action="start" --log_path="systemd" --line_match="Application started"

#=================================================
# END OF SCRIPT
#=================================================

# Let's wait a bit for migrations to happen
if [ ${PACKAGE_CHECK_EXEC:-0} -eq 1 ]; then
    sleep 5
fi

ynh_script_progression --message="Upgrade of $app completed" --last
